#import "../theme.typ": proof, proposition, definition, comment

= Measure Theory

#definition(text[$sigma$-algebra])[
    Let $X$ be a set. $Sigma subset.eq 2^X$ is said a *sigma algebra of X* iff.:
    1. $X in Sigma$
    2. $E in Sigma ==> X without E in Sigma$. #comment[close under complement].
    3. ${A_n in Sigma}_(n=1)^(oo) ==> union.big_(i=1)^(oo) A_i in Sigma$. #comment[close under infinite unions].
]<sigma-algebra>

#definition(text[generate $sigma$-algebra])[
    Let $X$ be a set and $G subset.eq 2^X$. The *$sigma$-algebra generated by $G$*, denoted $sigma_(X)(G)$, is the smallest #link(<sigma-algebra>)[$sigma$-algebra] such that:
    1. $G subset.eq sigma_(X)(G)$.
    2. $forall Sigma " "sigma"-algebra": G subset.eq Sigma ==> sigma_(X)(G) subset.eq Sigma$. #comment[Every other $sigma$-algebra that contains $G$ contains also the generated one, $sigma_(X)(G)$].
]<generated-sigma-algebra>

#definition(text[$sigma$-algebra product])[
    Let $Sigma_1$ and $Sigma_2$ be #link(<sigma-algebra>)[$sigma$-algebras] on $X_1$ and $X_2$ respectively. The *product $sigma$-algebra* denoted $Sigma_1 times.circle Sigma_2$ is defined as $#link(<generated-sigma-algebra>)[$sigma_(X_1 times X_2)$] ({S_1 times S_2 | S_1 in Sigma_1, S_2 in Sigma_2})$ 
]<sigma-algebra-product>

#definition("measurable space")[
    $(X,Sigma)$ is said *measurable* iff. #sym.Sigma is a #link(<sigma-algebra>)[sigma-algebra] of $X$.
]<measurable-space>
#show "measurable space": link(<measurable-space>)[measurable space]

#definition("measure")[
    Given $(X,Sigma)$ measurable space. $mu:Sigma --> RR union {+oo,-oo}$ is said a *measure* iff.
    1. $E in Sigma ==> mu(E)>=0$. #comment[positive].
    2. ${E_n in Sigma}_(n=1)^(oo) " such that " E_i sect E_j " for " i != j ==> mu(union.big_(i=1)^(oo) E_i) = sum_(i=1)^(oo) mu(E_i)$. #comment[The measure of disjoint sets is is the sum of the measures of each set].
    3. $exists E in Sigma : mu(E) in RR_(>=0)$. #comment[For at least an element $mu$ is finite].
]<measure>
#show "measure": link(<measure>)[measure]

#definition("measure space")[
    $(X,Sigma,mu)$ is said a *measure space* iff. $(X,Sigma)$ is a #link(<sigma-algebra>)[sigma algebra] and #sym.mu is a #link(<measure>)[measure] of $(X,Sigma)$.
]<measure-space>
#show "measure space": link(<measure-space>)[measure space]


#definition("measurable function")[
    Let $(X_1, Sigma_1)$ and $(X_2, Sigma_2)$ be a measurable spaces. $f X_1 --> X_2$ is said a *measurable function* iff. $forall E in Sigma_2: f^(-1)(E) in Sigma_1$. #comment[The pre-image of each measurable set is again measurable].
]<measurable-function>
#show "measurable function": link(<measurable-function>)[measurable function]

#definition("pushforward")[
    Let $(X_1,Sigma_1,mu)$ be a measure space. Let $(X_2,Sigma_2)$ be a measurable space. Let $f:X_1 --> X_2$ be a measurable function. The *pushforwad of #sym.mu under $f$* is the mapping $f_(\#)mu: Sigma_2 --> RR_(>=0)$ defined as: $ forall E in Sigma_2 : f_(\#)mu(E) = mu(f^(-1)(E)) $
]<pushforward>

#proposition("pushforward of a measure is a measure")[
    Let $(X_1,Sigma_1,mu)$ be a measure space. Let $(X_2,Sigma_2)$ be a measurable space. Let $f:X_1 --> X_2$ be a measurable function. Then $(X_2,Sigma_2,f_(\#)mu)$ is a measure space.
]<pushforward-of-a-measure-is-a-measure>
#show "pushforward": link(<pushforward>)[pushforward]

#proof(text[of @pushforward-of-a-measure-is-a-measure])[
    To prove that statement, we need to prove only the axioms of a measure.
    1. Let $E in Sigma_2$, we need to show that $f_(\#)mu(E) >= 0$. This is trivial by definition of pushforward and measure.
    2. Let $[E_n in Sigma_2]_(n=1)^(oo)$ be a sequence of pairwise disjoint sets. We need to show that: $f_(\#)mu(union.big_(n=1)^(oo)E_n)=sum_(n=1)^(oo)f_(\#)mu(E_n)$.
        $ f_(\#)mu(union.big_(n=1)^(oo)E_n) &= mu(f^(-1)(union.big_(n=1)^(oo) E_n)) #comment[definition of  pushforward] \
                                            &= mu(union.big_(n=1)^(oo) f^(-1)(E_n)) \
                                            &= sum_(n=1)^(oo) mu(f^(-1)(E_n)) #comment[definition of  measure] \
                                            &= sum_(n=1)^(oo) f_(\#)mu(E_n) #comment[definition of  pushforward]
        $
    3. We need to show that $exists E in Sigma_1$ such that $f_(\#)(E) >= 0$. Let $E' in Sigma_1$ such that $mu(E') >= 0$ (such $E'$ exists by defintion of measure). Then, $f(E')$ is a set that meets the requirements, that is 
        $ f_(\#)(f(E')) = mu(f^(-1)(f(E'))) = mu(E') >= 0 $
]
