#import "../theme.typ": definition, comment

= Measure Theory

#definition(text[$sigma$-algebra])[
    Let $X$ be a set. $Sigma subset.eq 2^X$ is said a *sigma algebra of X* iff.:
    1. $X in Sigma$
    2. $E in Sigma ==> X without E in Sigma$. #comment[close under complement].
    3. ${A_n in Sigma}_(n=1)^(oo) ==> union.big_(i=1)^(oo) A_i in Sigma$. #comment[close under infinite unions].
]<sigma-algebra>

#definition(text[generate $sigma$-algebra])[
    Let $X$ be a set and $G subset.eq 2^X$. The *$sigma$-algebra generated by $G$*, denoted $sigma(G)$, is the smallest #link(<sigma-algebra>)[$sigma$-algebra] such that:
    1. $G subset.eq sigma(G)$.
    2. $forall Sigma " "sigma"-algebra": G subset.eq Sigma ==> sigma(G) subset.eq Sigma$. #comment[Every other $sigma$-algebra that contains $G$ contains also the generated one, $sigma(G)$].
]<generated-sigma-algebra>

#definition(text[$sigma$-algebra product])[
    Let $Sigma_1$ and $Sigma_2$ be #link(<sigma-algebra>)[$sigma$-algebras] on $X_1$ and $X_2$ respectively. The *product $sigma$-algebra* denoted $Sigma_1 times.circle Sigma_2$ is defined as $#link(<generated-sigma-algebra>)[#sym.sigma] ({S_1 times S_2 | S_1 in Sigma_1, S_2 in Sigma_2})$ 
]<sigma-algebra-product>

#definition("measurable space")[
    $(X,Sigma)$ is said *measurable* iff. #sym.Sigma is a #link(<sigma-algebra>)[sigma-algebra] of $X$.
]<measurable-space>

#definition("measure")[
    Given $(X,Sigma)$ #link(<measurable-space>)[measurable space]. $mu:Sigma --> RR union {+oo,-oo}$ is said a *measure* iff.
    1. $E in Sigma ==> mu(E)>=0$. #comment[positive].
    2. ${E_n in Sigma}_(n=1)^(oo) " such that " E_i sect E_j " for " i != j ==> mu(union.big_(i=1)^(oo) E_i) = sum_(i=1)^(oo) mu(E_i)$. #comment[The measure of disjoint sets is is the sum of the measures of each set].
    3. $exists E in Sigma : mu(E) in RR_(>=0)$. #comment[For at least an element $mu$ is finite].
]<measure>

#definition("measure space")[
    $(X,Sigma,mu)$ is said a *measure space* iff. $(X,Sigma)$ is a #link(<sigma-algebra>)[sigma algebra] and #sym.mu is a #link(<measure>)[measure] of $(X,Sigma)$.
]<measure-space>


