#import "../theme.typ": proof, proposition, definition, example, comment

= Measure Theory

#definition("half open rectangle")[
    Let $a_0, b_0, ..., a_n, b_n in RR$. The set $times.big_(i=0)^n [a_i, b_i)$ is called an n-dimensional *half open rectangle*. The collection of all n-dimensional *half-open-rectangles* is denoted with $cal(I)^n_h$.
]<half-open-rectangle>
#show "half open rectangle": link(<half-open-rectangle>)[half open rectangle]

#definition("restriction")[
    Let $f:X --> Y$. Let $X' subset.eq X$. Let $Y'$ such that $f(X') subset.eq Y' subset.eq Y$. A *restriction of f over $X' times Y'$*, denoted $f|_(X' times Y')$ is a function $X' --> Y'$ such that $f|_(X times Y) = {(x,f(x)) | x in X, f(x) in Y}$
]<restriction>
#show "restriction": link(<restriction>)[restriction]

#example("restriction")[
    Let $f:RR-->RR$ such that $f(x) = x^2$ #comment[power operator over the real numbers]. Now, consider $g:NN-->NN$ such that $g(x) = x^2$ #comment[power operator over the natural number only]. Then $g$ is a restriction of f. 
    1. $NN subset.eq RR$.
    2. $f(NN) subset.eq NN subset.eq RR$.
    3. ${(x, g(x))| x in NN, y in NN)} subset.eq {(x,f(x)|x in RR, y in RR)}$
]

#definition("inverse function")[
    Let $f:X --> Y$ be a function. The *inverse function* $f^(-1): Y --> X$ is a function such that $f^(-1)(y in Y) = x in X$ if $f(x) = y$.
]<inverse-function>
#show "inverse function": link(<inverse-function>)[inverse function]

#definition("preimage")[
    Let $f:X --> Y$ be a function. Let $E subset.eq Y$. The *preimage* is the set $f^(-1)(E) = {x in X | f(x) in E}$.
]<preimage>
#show "preimage": link(<preimage>)[preimage]

#definition(text[$sigma$-algebra])[
    Let $X$ be a set. $Sigma subset.eq 2^X$ is said a *sigma algebra of X* iff.:
    1. $X in Sigma$
    2. $E in Sigma ==> X without E in Sigma$. #comment[close under complement].
    3. ${A_n in Sigma}_(n=1)^(oo) ==> union.big_(i=1)^(oo) A_i in Sigma$. #comment[close under infinite unions].
]<sigma-algebra>

#definition(text[generate $sigma$-algebra])[
    Let $X$ be a set and $G subset.eq 2^X$. The *$sigma$-algebra generated by $G$*, denoted $sigma_(X)(G)$, is the smallest #link(<sigma-algebra>)[$sigma$-algebra] such that:
    1. $G subset.eq sigma_(X)(G)$.
    2. $forall Sigma " "sigma"-algebra": G subset.eq Sigma ==> sigma_(X)(G) subset.eq Sigma$. #comment[Every other $sigma$-algebra that contains $G$ contains also the generated one, $sigma_(X)(G)$].
]<generated-sigma-algebra>

#definition(text[borel $sigma$-algebra])[
    Let $(X,G)$ be a topological space. We refer to $sigma_(X)(G)=cal(B)(X,G)$ as a *Borel $sigma$-algebra*.
]<borel-sigma-algebra>
#show "borel-sigma-algebra": link(<borel-sigma-algebra>)[Borel $sigma$-algebra]

#definition(text[$sigma$-algebra product])[
    Let $Sigma_1$ and $Sigma_2$ be #link(<sigma-algebra>)[$sigma$-algebras] on $X_1$ and $X_2$ respectively. The *product $sigma$-algebra* denoted $Sigma_1 times.circle Sigma_2$ is defined as $#link(<generated-sigma-algebra>)[$sigma_(X_1 times X_2)$] ({S_1 times S_2 | S_1 in Sigma_1, S_2 in Sigma_2})$ 
]<sigma-algebra-product>

#definition("measurable space")[
    $(X,Sigma)$ is said *measurable* iff. #sym.Sigma is a #link(<sigma-algebra>)[sigma-algebra] of $X$.
]<measurable-space>
#show "measurable space": link(<measurable-space>)[measurable space]

#definition("measure")[
    Given $(X,Sigma)$ measurable space. $mu:Sigma --> RR union {+oo,-oo}$ is said a *measure* iff.
    1. $E in Sigma ==> mu(E)>=0$. #comment[positive].
    2. ${E_n in Sigma}_(n=1)^(oo) " such that " E_i sect E_j " for " i != j ==> mu(union.big_(i=1)^(oo) E_i) = sum_(i=1)^(oo) mu(E_i)$. #comment[The measure of disjoint sets is is the sum of the measures of each set].
    3. $mu(nothing)=0$.
]<measure>
#show "measure": link(<measure>)[measure]

#definition("measure space")[
    $(X,Sigma,mu)$ is said a *measure space* iff. $(X,Sigma)$ is a #link(<sigma-algebra>)[sigma algebra] and #sym.mu is a #link(<measure>)[measure] of $(X,Sigma)$.
]<measure-space>
#show "measure space": link(<measure-space>)[measure space]

#definition("measurable function")[
    Let $(X_1, Sigma_1)$ and $(X_2, Sigma_2)$ be a measurable spaces. $f:X_1 --> X_2$ is said a *measurable function* iff. $forall E in Sigma_2: f^(-1)(E) in Sigma_1$. #comment[The preimage of each measurable set is again measurable].
]<measurable-function>
#show "measurable function": link(<measurable-function>)[measurable function]

#definition("pushforward")[
    Let $(X_1,Sigma_1,mu)$ be a measure space. Let $(X_2,Sigma_2)$ be a measurable space. Let $f:X_1 --> X_2$ be a measurable function. The *pushforwad of #sym.mu under $f$* is the mapping $f_(\#)mu: Sigma_2 --> RR_(>=0)$ defined as: $ forall E in Sigma_2 : f_(\#)mu(E) = mu(f^(-1)(E)) $
]<pushforward>
#show "pushforward": link(<pushforward>)[pushforward]

The pushforward is simply a function that generates a measure for a measurable space starting from a different measure space and a measurable function acting as bridge between the two spaces. 

#proposition("pushforward of a measure is a measure")[
    Let $(X_1,Sigma_1,mu)$ be a measure space. Let $(X_2,Sigma_2)$ be a measurable space. Let $f:X_1 --> X_2$ be a measurable function. Then $(X_2,Sigma_2,f_(\#)mu)$ is a measure space.
]<pushforward-of-a-measure-is-a-measure>

#proof(text[of @pushforward-of-a-measure-is-a-measure])[
    To prove that statement, we need to prove only the axioms of a measure.
    1. Let $E in Sigma_2$, we need to show that $f_(\#)mu(E) >= 0$. This is trivial by definition of pushforward and measure.
    2. Let $[E_n in Sigma_2]_(n=1)^(oo)$ be a sequence of pairwise disjoint sets. We need to show that: $f_(\#)mu(union.big_(n=1)^(oo)E_n)=sum_(n=1)^(oo)f_(\#)mu(E_n)$.
        $ f_(\#)mu(union.big_(n=1)^(oo)E_n) &= mu(f^(-1)(union.big_(n=1)^(oo) E_n)) #comment[definition of  pushforward] \
                                            &= mu(union.big_(n=1)^(oo) f^(-1)(E_n)) \
                                            &= sum_(n=1)^(oo) mu(f^(-1)(E_n)) #comment[definition of  measure] \
                                            &= sum_(n=1)^(oo) f_(\#)mu(E_n) #comment[definition of  pushforward]
        $
    3. We need to show that $exists E in Sigma_1$ such that $f_(\#)(E) >= 0$. Let $E' in Sigma_1$ such that $mu(E') >= 0$ (such $E'$ exists by defintion of measure). Then, $f(E')$ is a set that meets the requirements, that is 
        $ f_(\#)(f(E')) = mu(f^(-1)(f(E'))) = mu(E') >= 0 $
]

#example("pushforward example")[
    Consider the measure space $(NN,2^NN,mu(E)=|E|)$. Consider the measurable space $(RR, cal(B)(RR))$. Consider the measurable function $f:NN --> RR$ such that f(x) = x. Consider pushforward $f_(\#)mu:RR --> RR_(>=0)$. Then $f_(\#)mu$ is a measure for the measurable space $(RR, cal(B)(RR))$ since:
    1. $f_(\#)mu(E in cal(B)(RR)) = |{n in NN | n in E}| >= 0$.
    2. Let ${E_n}_(n=1)^(oo)$ pairwise disjoint, then $f_(\#)mu(union.big_(n=1)^(oo) E_n) = mu(f^(-1)(union.big_(n=1)^(oo) E_n)) = mu(union.big_(n=1)^(oo) f^(-1)(E_n)) = sum_(n=1)^(oo) mu(f^(-1)(E_n)) = sum_(n=1)^(oo) f_(\#)mu(E_n)$.
    3. $f_(\#)mu(nothing) = mu(f^(-1)(nothing)) = mu(nothing) = 0$
]

#include "lebesgue-measure.typ" 
